### ISSUE TITLE
[BUG] Red error screen after clicking “Did it”

### ISSUE THREAD

**Issue by bensonwallace** [rosenpin/Goaly#18]
**Describe the bug**
as per subject line

**To Reproduce**
Go to Google Calendar
Click Did it on a goal that Goaly has scheduled

**Expected behavior**
It usually gives a green screen with a tick

**Screenshots**
![image](https://user-images.githubusercontent.com/118611501/206890229-661efe6e-4012-42c3-aded-261602ef5d0a.png)

I'm using Google Chrome on Windows, both updated to latest versions.

**Comment by rosenpin** [comment]
Thanks for bringing it to our attention!  
We're aware of the issue and will be working to fix it ASAP!

**Comment by rosenpin** [comment]
Fixed  
You may have to clear cache/restart your browser for the changes to take effect
