### ISSUE TITLE
Suggestion: allow setting goals in a specific time/dates

### ISSUE THREAD

**Issue by itahol** [rosenpin/Goaly#2]
I have some goals I want to do in specific days (for example my usual workout days), or at specific times.
Right now, I can add them as usual reccuring events at Calendar, but having the ability to manage all of my goals in one place is very useful 😄 
In general the ability to have more control on certain goals is greatly appreciated.

**Comment by Kylerj500** [comment]
I agree! I love the automatic scheduling, but having the option for both would be nice

**Comment by rosenpin** [comment]
This is a bit out of scope for the app's original functionality but I think a lot of users (including me) could benefit from it.  
I'll probably add it in a future version of the app (maybe 2.0?)

**Comment by rosenpin** [comment]
Added in 1.1.7
