### ISSUE TITLE
[BUG] settings tab and upcoming mismatch on time format 

### ISSUE THREAD

**Issue by UltraSalem** [rosenpin/Goaly#25]
**Describe the bug**
I want to use a 24 hour clock. In the app settings it seems to respect my phone format setting of 24 hour time. But in the "upcoming" tab it uses 12 hour format, but does not include am or pm.

**Expected behavior**
Should be consistent with system setting. 24 hour time everywhere, or 12 hour time everywhere with am and pm.

**Screenshots**
![Screenshot_2023-01-08-12-17-20-62_91143ff9010ea047b9b69c149f29bd19](https://user-images.githubusercontent.com/5058207/211176429-d61a906c-3ecd-40c9-be81-7b9fa7d55260.jpg)

![Screenshot_2023-01-08-12-05-20-78_91143ff9010ea047b9b69c149f29bd19](https://user-images.githubusercontent.com/5058207/211176433-b576014c-b11c-4188-9b35-f7ae28ff0945.jpg)

**Smartphone (please complete the following information):**
 
![Screenshot_2023-01-08-12-11-08-19_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/5058207/211176441-e2073eb3-7983-41e8-ab92-e239e541c0cd.jpg)

System time settings
![Screenshot_2023-01-08-12-20-29-45_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/5058207/211176469-c0601551-2c25-4b26-8e33-cb75bd70458d.jpg)

**Additional context**

**Comment by rosenpin** [comment]
Thank you!  
We will look into fixing this in the next update of the app :)

**Comment by UltraSalem** [comment]
I'm now seeing 24 hour time in the "upcoming" tab, which is good. But now I've got issue #23 happening. 
![Screenshot_2023-01-11-20-57-22-71_3481fdfaf807158df2e382fd7e3ae703](https://user-images.githubusercontent.com/5058207/211776656-fbaef6b6-808d-46c9-937f-53d2a41e2421.jpg)
![Screenshot_2023-01-11-21-02-04-90_91143ff9010ea047b9b69c149f29bd19](https://user-images.githubusercontent.com/5058207/211776667-4795b5a3-8c0e-421e-a5c9-4cd834804609.jpg)

**Comment by rosenpin** [comment]
I think it's the same issue, we didn't fix the 24h format yet, 10:15-11:15 could still be 12h format  
this will be fixed in the next update

**Comment by rosenpin** [comment]
This was fixed in the previous update, only pushed to Android, will be updated on iOS as well next version
