### ISSUE TITLE
Suggestion: Adding a refresh button

### ISSUE THREAD

**Issue by Kylerj500** [rosenpin/Goaly#3]
I've noticed on Android, when I mark off a goal in the calendar if the Goaly app is opened in the background it will not show the goal as completed in the app. The only way I can get it to show up is if I close out the app and re-open it. I wonder if there could be an auto-refresh when you open the app, or maybe just a button to manually refresh.

**Comment by rosenpin** [comment]
Nice catch, will do in an upcoming update!

**Comment by rosenpin** [comment]
Implemented a while ago, swipe to refresh
