### ISSUE TITLE
[BUG] Goals don't appear in calendar

### ISSUE THREAD

**Issue by GzJmac** [rosenpin/Goaly#33]
**Describe the bug**
Goaly goals are not adding onto my Google Calendar

**To Reproduce**
1. Add goals in goaly
2. Does not show up on my google calendar

**Expected behavior**
I added a couple of goals, but it is not showing up on my google calendar. I made sure to link my correct Gmail account, and also ensured I had Goaly calendar checked in the google calendar settings for that email.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Iphone 13 Pro
 - OS: 16.3
 - App Version [e.g. 1.0.1]

**Additional context**
![IMG_4076](https://user-images.githubusercontent.com/125088140/218187706-f980cb3b-ea37-48a5-9e2a-ab092cae62e1.jpg)

**Comment by rosenpin** [comment]
Hi,  
Sorry for the late reply, was this solved?  
If not, please try to 
1. Remove Goaly from your Google account using [this link](https://myaccount.google.com/permissions?continue=https%3A%2F%2Fmyaccount.google.com%2Fsecurity)
2. Then uninstall->reinstall Goaly

Let me know if that worked

**Comment by rosenpin** [comment]
Closed due to inactivity

**Comment by GzJmac** [comment]
It just literally never ended up working for my google  calendar. I tried
reinstalling goaly.

**Comment by rosenpin** [comment]
Is it possible that you might have an all day event in your google calendar every day?

Possible duplicate of https://github.com/rosenpin/Goaly/issues/15
