### ISSUE TITLE
[FEATURE] Add function to reschedule habits

### ISSUE THREAD

**Issue by Kimibelle** [rosenpin/Goaly#34]
Problem:
Sometimes plans change and being able to reschedule habits would be useful.

Solution:
Add a button that reschedules habits for later.

**Comment by ghost** [comment]
I also would like to be able to easily reschedule to an earlier time. Eg I have some time and complete a goal that has been scheduled for the nextt day, the task should be moved to today's and future occurrences should automatically be rescheduled

**Comment by rosenpin** [comment]
Thank you for the great suggestion!  
We already have an open issue for this suggestion, please check it out here and feel free to leave a comment there:: https://github.com/rosenpin/Goaly/issues/8

**Comment by rosenpin** [comment]
Duplicate of #8
