### ISSUE TITLE
Color of navigation bar changes

### ISSUE THREAD

**Issue by tomer8007** [rosenpin/Goaly#5]
I noticed that in the Goal Overview page, whenever I start changing the frequency of the goal from "Once" to something else, the color of the navigation bar at the top changes:

White navigation bar             |  Tinted navigation bar
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11458759/200119421-40987e13-11dd-4a31-8afe-655fe0d6484b.png)  |  ![](https://user-images.githubusercontent.com/11458759/200119425-a1ddbe20-49c2-4df5-859b-79a279d19e04.png )

I don't know whether this is an intentional behavior, but it feels like this should not happen.

**Comment by rosenpin** [comment]
צודק זה באג  
תודה חדד 🙏

**Comment by rosenpin** [comment]
Fixed and will be updated in version 1.1.1
