### ISSUE TITLE
[BUG] Notification settings do not appear to update when set

### ISSUE THREAD

**Issue by eiron** [rosenpin/Goaly#57]
**Describe the bug**
Notification settings do not seem to update (though they do)

**To Reproduce**
1. Go to Settings
2. Click on Notifications time
3. Set time as desired
4. Time is set correctly (closing and reopening settings shows this), but it does not provide the instant on-screen feedback you would expect

**Expected behavior**
Correct notification time should display here when set.

**Screenshots**
N/A.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: OxygenOS 13.0/Android 13
 - App Version 1.1.7

**Additional context**
N/A

**Comment by rosenpin** [comment]
I can't reproduce this. Can you please send a screen recording of this issue?

**Comment by eiron** [comment]
I cannot. Tried to reproduce myself and it worked fine. A passing glitch? Something that got resolved in an update? I have no idea. We can close this.
