### ISSUE TITLE
No reschedule on time settings change 

### ISSUE THREAD

**Issue by DMeredith88** [rosenpin/Goaly#58]
Changing evenings to end at 9pm for example doesn't reschedule tasks for goals already set at 10pm.

**Comment by rosenpin** [comment]
Thanks for the feedback  
This is a duplicate of https://github.com/rosenpin/Goaly/issues/54  
Feel free to follow this issue instead

**Comment by DMeredith88** [comment]
Didn't see that one! Thanks :)
