### ISSUE TITLE
[BUG]  when selecting frequency of of goal, it only gives "a week".  A month or a year are not available

### ISSUE THREAD

**Issue by lezette18** [rosenpin/Goaly#64]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by rosenpin** [comment]
Hi,  
Thank you for the feedback :)  
There is already an open issue regarding this feature request here:  https://github.com/rosenpin/Goaly/issues/11

I'm closing this one, you may follow the progress on this issue from the link above
